### ISSUE TITLE
node/ai-knowledge-assistant does not deploy properly

### ISSUE THREAD

**Issue by deoomen** [googleworkspace/google-chat-samples#282]
There is an error when trying to deploy node/ai-knowledge-assistant app:

```
Build failed with status: FAILURE and message: function.js does not exist.
```

Logs:

```
Step #2 - "build": failed to build: (error ID: 7485c5b6):
Step #2 - "build": function.js does not exist
```

**Comment by IvBos023** [comment]
Yeah, I ran into the same issue.
Can't get around it.

**Comment by gtondello** [comment]
Thank you for trying our sample! I believe the issue may be that you are deploying the function to Google Cloud with a zip file, but you added the folder `ai-knowledge-assistant` to the zip file.

For the deployment to work, you must zip the contents of the folder (i.e., the files within the folder), not the folder itself. If you open the zip file, you should see `package.json`, `index.js`, and other files and subfolders in the root, not the folder `ai-knowledge-assistant`.

Please let us know if that resolves the issue.

**Comment by robforee** [comment]
Same issue which that did no resolve. There is no function.js file in the repo, nor mention of the functions in the https://developers.google.com/workspace/chat/tutorial-ai-knowledge-assistant.
no steps in the quickstart to create the functions.
