### ISSUE TITLE
"apps-script/chat-apps-gemini"  repository does not exit

### ISSUE THREAD

**Issue by hideyuki-ogawa** [googleworkspace/google-chat-samples#301]
https://github.com/googleworkspace/google-chat-samples/tree/main/apps-script/chat-apps-gemini

404 page not found.

**Comment by PierrickVoulet** [comment]
Hi @hideyuki-ogawa,

The content of this location was moved [here](https://github.com/googleworkspace/google-chat-samples/tree/main/apps-script/issue-management-app). Could you please tell where you got this link so that we can fix it?

**Comment by hideyuki-ogawa** [comment]
Hi @PierrickVoulet 

Thank you for your reply. I found this link in codellab: build apps for Google Chat with Gemini.
URL: https://codelabs.developers.google.com/codelabs/chat-apps-gemini?hl=en#1

**Comment by PierrickVoulet** [comment]
Thanks! Most of the links should be fix now. Please reload the codelab to get the updated version.
